### ISSUE TITLE
How does it work?

### ISSUE THREAD

**Issue by LittleUnicat** [Takak11/recruit#1]
How dos it work?
Can you teach me?
😁🤣😍

**Comment by Takak11** [comment]
> LittleUnicat

turtle with babershop

**Comment by LittleUnicat** [comment]
> > LittleUnicat
> 
> turtle with babershop

💈
🐢

**Comment by LittleUnicat** [comment]
I've already hanked this project.

**Comment by Takak11** [comment]
> I've already hanked this project.

WTF
